/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 muerren-allmendhubel.glb --keepnames --keepmeshes --keepgroups 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/muerren-allmendhubel.glb')
  return (
    <group {...props} dispose={null}>
        <group name="Mürren-Allmendhubel" position={[2108.395, 1737.734, 1079.673]}>
          <instancedMesh args={[nodes['stop-mesh'].geometry, materials.silver_dark, 2]} name="stop-mesh" instanceMatrix={nodes['stop-mesh'].instanceMatrix} />
          <instancedMesh args={[nodes['stop-mesh_1'].geometry, materials['black.002'], 2]} name="stop-mesh_1" instanceMatrix={nodes['stop-mesh_1'].instanceMatrix} />
          <instancedMesh args={[nodes['stop-mesh_2'].geometry, materials['silver.002'], 2]} name="stop-mesh_2" instanceMatrix={nodes['stop-mesh_2'].instanceMatrix} />
          <instancedMesh args={[nodes['stop-mesh_3'].geometry, materials.red, 2]} name="stop-mesh_3" instanceMatrix={nodes['stop-mesh_3'].instanceMatrix} />
          <group name="Connection_Mürren-Allmendhubel" position={[-2108.395, -1737.734, -1079.673]}>
            <group name="Cable-Bottom001" position={[2221.532, 1616.309, 1237.213]} />
            <group name="Cable-Top001" position={[1995.259, 1859.158, 922.134]} />
            <mesh name="Cable001" geometry={nodes.Cable001.geometry} material={materials['Material.009']} position={[2108.395, 1737.734, 1079.673]} />
          </group>
        </group>
      </group>
  )
}

useGLTF.preload('/muerren-allmendhubel.glb')
