/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 restaurantsHigh.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import restaurantsHigh from "../../assets/testGLTF/restaurantsHigh.glb";

const RestaurantsHigh = (props) => {
  const { nodes, materials } = useGLTF(restaurantsHigh);

  const moveX = 4105.2;
  const moveY = 375.45;
  const moveZ = -4437.3;

  return (
    <group dispose={null}>
      <group {...props} position={[4006.509-moveX, 2383.354-moveY, -4213.081-moveZ]} rotation={[Math.PI, -0.838, Math.PI]}>
        <mesh geometry={nodes.Cube037.geometry} material={materials['Dark_wood.012']} />
        <mesh geometry={nodes.Cube037_1.geometry} material={materials['Light_wood.012']} />
        <mesh geometry={nodes.Cube037_2.geometry} material={materials['Glass.014']} />
        <mesh geometry={nodes.Cube037_3.geometry} material={materials['grey.012']} />
        <mesh geometry={nodes.Cube037_4.geometry} material={materials['Black.012']} />
        <mesh geometry={nodes.Cube037_5.geometry} material={materials['fundament.003']} />
      </group>
      <group {...props} position={[3626.483-moveX, 2626.613-moveY, -3316.086-moveZ]} rotation={[0, 0.047, 0]}>
        <mesh geometry={nodes.Cube038.geometry} material={materials['Dark_wood.013']} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials['Light_wood.013']} />
        <mesh geometry={nodes.Cube038_2.geometry} material={materials['Glass.015']} />
        <mesh geometry={nodes.Cube038_3.geometry} material={materials['grey.013']} />
        <mesh geometry={nodes.Cube038_4.geometry} material={materials['Black.013']} />
        <mesh geometry={nodes.Cube038_5.geometry} material={materials['fundament.004']} />
      </group>
      <group {...props} position={[5413.986-moveX, 1749.464-moveY, -2055.877-moveZ]} rotation={[0, -0.36, 0]}>
        <mesh geometry={nodes.Cube041.geometry} material={materials['Dark_wood.014']} />
        <mesh geometry={nodes.Cube041_1.geometry} material={materials['Light_wood.014']} />
        <mesh geometry={nodes.Cube041_2.geometry} material={materials['Glass.016']} />
        <mesh geometry={nodes.Cube041_3.geometry} material={materials['grey.014']} />
        <mesh geometry={nodes.Cube041_4.geometry} material={materials['Black.014']} />
        <mesh geometry={nodes.Cube041_5.geometry} material={materials['fundament.005']} />
      </group>
      <group {...props} position={[5462.128-moveX, 1786.315-moveY, -3476.51-moveZ]} rotation={[0, -0.458, 0]}>
        <mesh geometry={nodes.Cube042.geometry} material={materials['Dark_wood.015']} />
        <mesh geometry={nodes.Cube042_1.geometry} material={materials['Light_wood.015']} />
        <mesh geometry={nodes.Cube042_2.geometry} material={materials['Glass.017']} />
        <mesh geometry={nodes.Cube042_3.geometry} material={materials['grey.015']} />
        <mesh geometry={nodes.Cube042_4.geometry} material={materials['Black.015']} />
        <mesh geometry={nodes.Cube042_5.geometry} material={materials['fundament.006']} />
      </group>
      <group {...props} position={[5310.06-moveX, 1802.154-moveY, -3209.324-moveZ]} rotation={[0, -1.421, 0]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials['Dark_wood.016']} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials['Light_wood.016']} />
        <mesh geometry={nodes.Cube043_2.geometry} material={materials['Glass.018']} />
        <mesh geometry={nodes.Cube043_3.geometry} material={materials['grey.016']} />
        <mesh geometry={nodes.Cube043_4.geometry} material={materials['Black.016']} />
        <mesh geometry={nodes.Cube043_5.geometry} material={materials['fundament.007']} />
      </group>
      <group {...props} position={[6008.853-moveX, 1863.267-moveY, -3559.4-moveZ]} rotation={[Math.PI, -0.179, Math.PI]}>
        <mesh geometry={nodes.Cube044.geometry} material={materials['Dark_wood.017']} />
        <mesh geometry={nodes.Cube044_1.geometry} material={materials['Light_wood.017']} />
        <mesh geometry={nodes.Cube044_2.geometry} material={materials['Glass.019']} />
        <mesh geometry={nodes.Cube044_3.geometry} material={materials['grey.017']} />
        <mesh geometry={nodes.Cube044_4.geometry} material={materials['Black.017']} />
        <mesh geometry={nodes.Cube044_5.geometry} material={materials['fundament.008']} />
      </group>
      <group {...props} position={[4724.088-moveX, 2076.181-moveY, -2825.065-moveZ]} rotation={[-Math.PI, 0.088, -Math.PI]}>
        <mesh geometry={nodes.Cube045.geometry} material={materials['Dark_wood.018']} />
        <mesh geometry={nodes.Cube045_1.geometry} material={materials['Light_wood.018']} />
        <mesh geometry={nodes.Cube045_2.geometry} material={materials['Glass.020']} />
        <mesh geometry={nodes.Cube045_3.geometry} material={materials['grey.018']} />
        <mesh geometry={nodes.Cube045_4.geometry} material={materials['Black.018']} />
        <mesh geometry={nodes.Cube045_5.geometry} material={materials['fundament.009']} />
      </group>
      <group {...props} position={[1891.725-moveX, 2916.482-moveY, -2802.719-moveZ]} rotation={[-Math.PI, 0.445, -Math.PI]}>
        <mesh geometry={nodes.Cube046.geometry} material={materials['Dark_wood.019']} />
        <mesh geometry={nodes.Cube046_1.geometry} material={materials['Light_wood.019']} />
        <mesh geometry={nodes.Cube046_2.geometry} material={materials['Glass.021']} />
        <mesh geometry={nodes.Cube046_3.geometry} material={materials['grey.019']} />
        <mesh geometry={nodes.Cube046_4.geometry} material={materials['Black.019']} />
        <mesh geometry={nodes.Cube046_5.geometry} material={materials['fundament.010']} />
      </group>
      <group {...props} position={[6601.894-moveX, 1531.755-moveY, -5541.02-moveZ]}>
        <mesh geometry={nodes.Cube047.geometry} material={materials['Dark_wood.020']} />
        <mesh geometry={nodes.Cube047_1.geometry} material={materials['Light_wood.020']} />
        <mesh geometry={nodes.Cube047_2.geometry} material={materials['Glass.022']} />
        <mesh geometry={nodes.Cube047_3.geometry} material={materials['grey.020']} />
        <mesh geometry={nodes.Cube047_4.geometry} material={materials['Black.020']} />
        <mesh geometry={nodes.Cube047_5.geometry} material={materials['fundament.011']} />
      </group>
    </group>
  )
}

useGLTF.preload(restaurantsHigh)

export default RestaurantsHigh;
