/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 slopes.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/slopes.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Abfahrt-23'].geometry} material={materials['Material.003']} position={[1217.336, 2057.602, 1946.165]} scale={0.542} />
      <mesh geometry={nodes['Abfahrt-15'].geometry} material={materials['Material.010']} position={[158.751, 2856.949, 102.661]} rotation={[-Math.PI, 1.439, -Math.PI]} scale={0.542} />
      <mesh geometry={nodes['Abfahrt-10'].geometry} material={materials['Material.009']} position={[-2111.764, 2941.232, 1629.646]} rotation={[-Math.PI, 1.439, -Math.PI]} scale={0.542} />
      <mesh geometry={nodes['Abfahrt-3'].geometry} material={materials['Material.012']} position={[2459.159, 1629.303, -1147.965]} rotation={[-Math.PI, 0.129, -Math.PI]} scale={0.542} />
    </group>
  )
}

useGLTF.preload('/slopes.glb')
